import { writeFile, readFile, stat } from "node:fs/promises";
import { join } from "node:path";
import type { ScanResult } from "../types.js";

async function fileExists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

function generateContext(result: ScanResult): string {
  const { project, routes, schemas, components, middleware, config, graph } = result;

  const lines: string[] = [];

  // Stack overview
  const fw = project.frameworks.join(", ") || "generic";
  const orm = project.orms.join(", ") || "none";
  lines.push(`This is a ${project.language} project using ${fw}${orm !== "none" ? ` with ${orm}` : ""}.`);

  if (project.isMonorepo) {
    const repoLabel = project.repoType === "meta" ? "meta-repo"
      : project.repoType === "microservices" ? "microservices repo"
      : "monorepo";
    lines.push(`It is a ${repoLabel} with workspaces: ${project.workspaces.map((w) => `${w.name} (${w.path})`).join(", ")}.`);
  }

  lines.push("");

  // Key architecture facts
  if (routes.length > 0) {
    lines.push(`The API has ${routes.length} routes. See .boocontext/routes.md for the full route map with methods, paths, and tags.`);
  }
  if (schemas.length > 0) {
    lines.push(`The database has ${schemas.length} models. See .boocontext/schema.md for the full schema with fields, types, and relations.`);
  }
  if (components.length > 0) {
    lines.push(`The UI has ${components.length} components. See .boocontext/components.md for the full list with props.`);
  }
  if (middleware.length > 0) {
    const types = [...new Set(middleware.map((m) => m.type))].join(", ");
    lines.push(`Middleware includes: ${types}.`);
  }

  lines.push("");

  // Hot files (most imported = most impactful to change)
  if (graph.hotFiles.length > 0) {
    lines.push("High-impact files (most imported, changes here affect many other files):");
    for (const hf of graph.hotFiles.slice(0, 8)) {
      lines.push(`- ${hf.file} (imported by ${hf.importedBy} files)`);
    }
    lines.push("");
  }

  // Required env vars
  const requiredEnvs = config.envVars.filter((e) => !e.hasDefault);
  if (requiredEnvs.length > 0) {
    lines.push("Required environment variables (no defaults):");
    for (const env of requiredEnvs.slice(0, 15)) {
      lines.push(`- ${env.name} (${env.source})`);
    }
    lines.push("");
  }

  // Plugin-contributed sections
  if (result.customSections) {
    for (const cs of result.customSections) {
      const safeName = cs.name.replace(/[^a-z0-9_-]/gi, "").toLowerCase();
      if (!safeName) continue;
      lines.push(`See .boocontext/${safeName}.md for additional ${safeName} context.`);
    }
    lines.push("");
  }

  // Wiki reference if it exists
  lines.push("Read .boocontext/wiki/index.md for orientation (WHERE things live). Then read actual source files before implementing. Wiki articles are navigation aids, not implementation guides.");
  lines.push("Read .boocontext/BOOCONTEXT.md for the complete AI context map including all routes, schema, components, libraries, config, middleware, and dependency graph.");

  return lines.join("\n");
}

export async function generateAIConfigs(
  result: ScanResult,
  root: string
): Promise<string[]> {
  const generated: string[] = [];
  const context = generateContext(result);

  // --- CLAUDE.md ---
  const claudePath = join(root, "CLAUDE.md");
  const claudeExists = await fileExists(claudePath);
  if (!claudeExists) {
    const claudeContent = `# Project Context

${context}
`;
    await writeFile(claudePath, claudeContent);
    generated.push("CLAUDE.md");
  } else {
    // Check if it already references boocontext
    const existing = await readFile(claudePath, "utf-8");
    if (!existing.includes("boocontext") && !existing.includes("BOOCONTEXT")) {
      // Append context section
      const appendSection = `

# AI Context (auto-generated by boocontext)

${context}
`;
      await writeFile(claudePath, existing + appendSection);
      generated.push("CLAUDE.md (appended)");
    }
  }

  // --- .cursorrules ---
  const cursorPath = join(root, ".cursorrules");
  const cursorExists = await fileExists(cursorPath);
  if (!cursorExists) {
    const cursorContent = `# Project Context

${context}
`;
    await writeFile(cursorPath, cursorContent);
    generated.push(".cursorrules");
  }

  // --- .github/copilot-instructions.md ---
  const copilotDir = join(root, ".github");
  const copilotPath = join(copilotDir, "copilot-instructions.md");
  const copilotExists = await fileExists(copilotPath);
  if (!copilotExists) {
    // Only create if .github dir exists (don't create it for non-GitHub projects)
    const ghDirExists = await fileExists(copilotDir);
    if (ghDirExists) {
      const copilotContent = `# Project Context

${context}
`;
      await writeFile(copilotPath, copilotContent);
      generated.push(".github/copilot-instructions.md");
    }
  }

  // --- codex.md (OpenAI Codex CLI) ---
  const codexPath = join(root, "codex.md");
  const codexExists = await fileExists(codexPath);
  if (!codexExists) {
    const codexContent = `# Project Context

${context}
`;
    await writeFile(codexPath, codexContent);
    generated.push("codex.md");
  }

  // --- AGENTS.md (OpenAI Codex) ---
  const agentsPath = join(root, "AGENTS.md");
  const agentsExists = await fileExists(agentsPath);
  if (!agentsExists) {
    const agentsContent = `# Project Context

${context}
`;
    await writeFile(agentsPath, agentsContent);
    generated.push("AGENTS.md");
  }

  return generated;
}

/**
 * Generate a profile-specific config file optimized for a particular AI tool.
 * Includes tool-specific instructions on how to use boocontext outputs.
 */
export async function generateProfileConfig(
  result: ScanResult,
  root: string,
  profile: string
): Promise<string> {
  const { project, routes, schemas, graph, config } = result;

  // Build a compact always-load summary (~1-2k tokens)
  const summaryLines: string[] = [];
  summaryLines.push(`# ${project.name} — Project Context\n`);
  summaryLines.push(`**Stack:** ${project.frameworks.join(", ") || "generic"} | ${project.orms.join(", ") || "none"} | ${project.language}`);
  if (project.isMonorepo) {
    const repoLabel = project.repoType === "meta" ? "Meta-repo"
      : project.repoType === "microservices" ? "Microservices"
      : "Monorepo";
    summaryLines.push(`**${repoLabel}:** ${project.workspaces.map((w) => w.name).join(", ")}`);
  }
  summaryLines.push(`\n${routes.length} routes | ${schemas.length} models | ${config.envVars.length} env vars | ${graph.edges.length} import links\n`);

  // Top entry points
  if (routes.length > 0) {
    const areas = [...new Set(routes.map((r) => r.path.split("/").slice(0, 3).join("/")))].slice(0, 10);
    summaryLines.push(`**API areas:** ${areas.join(", ")}`);
  }

  // High-impact files
  if (graph.hotFiles.length > 0) {
    summaryLines.push(`\n**High-impact files** (change carefully):`);
    for (const hf of graph.hotFiles.slice(0, 5)) {
      summaryLines.push(`- ${hf.file} (imported by ${hf.importedBy} files)`);
    }
  }

  // Required env
  const required = config.envVars.filter((e) => !e.hasDefault);
  if (required.length > 0) {
    summaryLines.push(`\n**Required env vars:** ${required.map((e) => e.name).join(", ")}`);
  }

  summaryLines.push(`\n---\n`);

  // Profile-specific instructions
  switch (profile) {
    case "claude-code": {
      summaryLines.push(`## Instructions for Claude Code\n`);
      summaryLines.push(`### Two-Step Rule (mandatory)`);
      summaryLines.push(`**Step 1 — Orient:** Use wiki articles to find WHERE things live.`);
      summaryLines.push(`**Step 2 — Verify:** Read the actual source files listed in the wiki article BEFORE writing any code.\n`);
      summaryLines.push(`Wiki articles are structural summaries extracted by AST. They show routes, models, and file locations.`);
      summaryLines.push(`They do NOT show full function logic, middleware internals, or dynamic runtime behavior.`);
      summaryLines.push(`**Never write or modify code based solely on wiki content — always read source files first.**\n`);
      summaryLines.push(`Read in order at session start:`);
      summaryLines.push(`1. \`.boocontext/wiki/index.md\` — orientation map (~200 tokens)`);
      summaryLines.push(`2. \`.boocontext/wiki/overview.md\` — architecture overview (~500 tokens)`);
      summaryLines.push(`3. Domain article (e.g. \`.boocontext/wiki/auth.md\`) → check "Source Files" section → read those files`);
      summaryLines.push(`4. \`.boocontext/BOOCONTEXT.md\` — full context map for deep exploration\n`);
      summaryLines.push(`Routes marked \`[inferred]\` in wiki articles were detected via regex — verify against source before trusting.`);
      summaryLines.push(`If any source file shows ⚠ in the wiki, re-run \`npx boocontext --wiki\` before proceeding.\n`);
      summaryLines.push(`Or use the boocontext MCP server for on-demand queries:`);
      summaryLines.push(`   - \`boocontext_get_wiki_article\` — read a specific wiki article by name`);
      summaryLines.push(`   - \`boocontext_get_wiki_index\` — get the wiki index`);
      summaryLines.push(`   - \`boocontext_get_summary\` — quick project overview`);
      summaryLines.push(`   - \`boocontext_get_routes --prefix /api/users\` — filtered routes`);
      summaryLines.push(`   - \`boocontext_get_blast_radius --file src/lib/db.ts\` — impact analysis before changes`);
      summaryLines.push(`   - \`boocontext_get_schema --model users\` — specific model details`);
      summaryLines.push(`\nOnly open specific files after consulting boocontext context. This saves ~${result.tokenStats.saved.toLocaleString()} tokens per conversation.`);
      const outPath = join(root, "CLAUDE.md");
      const existing = await fileExists(outPath) ? await readFile(outPath, "utf-8") : "";
      if (existing && existing.includes("boocontext")) {
        await writeFile(outPath, existing.replace(/# AI Context.*?(?=\n#|\n$|$)/s, summaryLines.join("\n")));
      } else if (existing) {
        await writeFile(outPath, existing + "\n\n" + summaryLines.join("\n"));
      } else {
        await writeFile(outPath, summaryLines.join("\n"));
      }
      return "CLAUDE.md";
    }
    case "cursor": {
      summaryLines.push(`## Instructions for Cursor\n`);
      summaryLines.push(`When answering questions about this project:`);
      summaryLines.push(`1. Read \`.boocontext/BOOCONTEXT.md\` first for full project structure`);
      summaryLines.push(`2. Use \`.boocontext/routes.md\` to find relevant API handlers`);
      summaryLines.push(`3. Use \`.boocontext/schema.md\` to understand data models`);
      summaryLines.push(`4. Use \`.boocontext/graph.md\` to check blast radius before changes`);
      summaryLines.push(`\nDo not crawl the file tree — the boocontext context map already contains the full project structure.`);
      await writeFile(join(root, ".cursorrules"), summaryLines.join("\n"));
      return ".cursorrules";
    }
    case "codex": {
      summaryLines.push(`## Instructions for OpenAI Codex\n`);
      summaryLines.push(`This project uses boocontext for structured context. Read .boocontext/BOOCONTEXT.md before exploring files.`);
      summaryLines.push(`Routes: .boocontext/routes.md | Schema: .boocontext/schema.md | Dependencies: .boocontext/graph.md`);
      await writeFile(join(root, "codex.md"), summaryLines.join("\n"));
      return "codex.md";
    }
    case "copilot": {
      summaryLines.push(`## Instructions for GitHub Copilot\n`);
      summaryLines.push(`Project context is pre-generated in .boocontext/. Consult BOOCONTEXT.md for full architecture.`);
      const ghDir = join(root, ".github");
      await fileExists(ghDir) || await (await import("node:fs/promises")).mkdir(ghDir, { recursive: true });
      await writeFile(join(ghDir, "copilot-instructions.md"), summaryLines.join("\n"));
      return ".github/copilot-instructions.md";
    }
    case "windsurf": {
      summaryLines.push(`## Instructions for Windsurf\n`);
      summaryLines.push(`Read .boocontext/BOOCONTEXT.md for full project map before exploring files.`);
      summaryLines.push(`Use .boocontext/routes.md for API structure and .boocontext/graph.md for dependency analysis.`);
      await writeFile(join(root, ".windsurfrules"), summaryLines.join("\n"));
      return ".windsurfrules";
    }
    case "agents": {
      // Generate ONLY AGENTS.md — for local models and cross-platform AI agents
      // that follow the AGENTS.md standard (OpenAI Codex, local LLMs, etc.)
      summaryLines.push(`## Agent Instructions\n`);
      summaryLines.push(`This project uses boocontext for structured AI context. Follow these steps before implementing:`);
      summaryLines.push(`1. Read \`.boocontext/wiki/index.md\` for project orientation (~200 tokens)`);
      summaryLines.push(`2. Read \`.boocontext/wiki/overview.md\` for architecture overview (~500 tokens)`);
      summaryLines.push(`3. Read the relevant domain article, then open the source files listed in it`);
      summaryLines.push(`4. Read \`.boocontext/BOOCONTEXT.md\` for the full context map\n`);
      summaryLines.push(`**Do not explore the file tree blindly.** The boocontext context map already contains:`);
      summaryLines.push(`routes, schema, components, libraries, config, middleware, and dependency graph.\n`);
      summaryLines.push(`**Before modifying any file:** check \`.boocontext/graph.md\` for blast radius.`);
      summaryLines.push(`Files with high import counts affect many downstream modules — change carefully.\n`);
      summaryLines.push(`Routes marked \`[inferred]\` were detected via regex and may have lower precision.`);
      summaryLines.push(`If any source file shows ⚠ in a wiki article, re-run \`npx boocontext --wiki\` before proceeding.`);
      await writeFile(join(root, "AGENTS.md"), summaryLines.join("\n"));
      return "AGENTS.md";
    }
    default: {
      // Generic profile — write all configs
      const generated = await generateAIConfigs(result, root);
      return generated.join(", ") || "all configs already exist";
    }
  }
}

function generateMonorepoContext(
  packages: Array<{ name: string; dir: string }>,
  outputDirName: string
): string {
  const lines = [
    `This is a monorepo with ${packages.length} package${packages.length !== 1 ? "s" : ""} indexed by boocontext.`,
    `Read \`.${outputDirName}/BOOCONTEXT.md\` for the full package index — it lists every package that has a context file.`,
    ``,
    `Before exploring a package directory, check if \`<package>/.${outputDirName}/BOOCONTEXT.md\` exists — faster than grep/find.`,
    `Use \`<package>/.${outputDirName}/deps.md\` to find cross-package dependencies.`,
    ``,
    `Do not crawl the file tree — use the boocontext index instead.`,
  ];
  return lines.join("\n");
}

/**
 * Generate AI config files (CLAUDE.md, .cursorrules, etc.) with monorepo-appropriate content.
 * Uses the same append-if-exists logic as generateAIConfigs for single-project mode.
 */
export async function generateMonorepoAIConfigs(
  root: string,
  packages: Array<{ name: string; dir: string }>,
  outputDirName: string
): Promise<string[]> {
  const generated: string[] = [];
  const context = generateMonorepoContext(packages, outputDirName);

  // --- CLAUDE.md ---
  const claudePath = join(root, "CLAUDE.md");
  if (!(await fileExists(claudePath))) {
    await writeFile(claudePath, `# Project Context\n\n${context}\n`);
    generated.push("CLAUDE.md");
  } else {
    const existing = await readFile(claudePath, "utf-8");
    if (!existing.includes("boocontext") && !existing.includes("BOOCONTEXT")) {
      await writeFile(claudePath, existing + `\n\n# AI Context (auto-generated by boocontext)\n\n${context}\n`);
      generated.push("CLAUDE.md (appended)");
    }
  }

  // --- .cursorrules ---
  const cursorPath = join(root, ".cursorrules");
  if (!(await fileExists(cursorPath))) {
    await writeFile(cursorPath, `# Project Context\n\n${context}\n`);
    generated.push(".cursorrules");
  }

  // --- .github/copilot-instructions.md ---
  const copilotDir = join(root, ".github");
  const copilotPath = join(copilotDir, "copilot-instructions.md");
  if (!(await fileExists(copilotPath)) && await fileExists(copilotDir)) {
    await writeFile(copilotPath, `# Project Context\n\n${context}\n`);
    generated.push(".github/copilot-instructions.md");
  }

  // --- codex.md ---
  const codexPath = join(root, "codex.md");
  if (!(await fileExists(codexPath))) {
    await writeFile(codexPath, `# Project Context\n\n${context}\n`);
    generated.push("codex.md");
  }

  // --- AGENTS.md ---
  const agentsPath = join(root, "AGENTS.md");
  if (!(await fileExists(agentsPath))) {
    await writeFile(agentsPath, `# Project Context\n\n${context}\n`);
    generated.push("AGENTS.md");
  }

  // --- .windsurfrules ---
  const windPath = join(root, ".windsurfrules");
  if (!(await fileExists(windPath))) {
    await writeFile(windPath, `# Project Context\n\n${context}\n`);
    generated.push(".windsurfrules");
  }

  return generated;
}
